/*
    This header file is generated by sotom at 2022-07-22 23:23:16.839122
    visit sotom at https://github.com/sislamrafi/sotom
*/

#ifndef __LIBS__FLASH_H__
#define __LIBS__FLASH_H__

#include "../../main/board.h"

//define all your function prototypes and variables under this line
#define FLASH_DATA_SECTOR 7
#define FLASH_DATA_SECTOR_START 0x08060000
#define FLASH_DATA_SECTOR_STATUS_BYTE_ADDR 0x08060000
#define FLASH_DATA_SECTOR_STATUS_BYTE_POS 0

void unlockFlash();
void lockFlash();
void eraseDataSectorIfNeed();
void flashDataSectorEraseNeed();
void flash_data_write8t(uint8_t data, uint32_t position);
uint8_t flash_data_read8t(uint32_t position);

#endif
